### ISSUE TITLE
Not Work on Nexus 5 device 

### ISSUE THREAD

**Issue by bhoomikaPrajapati** [abangfadli/shotwatch#1] opened 2018-02-27 07:10 UTC

**Comment by abangfadli** [comment] 2018-03-01 08:35
Hi @bhoomikaPrajapati thanks for your report. Do you get any output on the logcat?
And what is the device OS version + your device language? Thanks.

**Comment by overhound** [comment] 2018-03-13 01:43
Have you been able to fix this? @abangfadli

**Comment by abangfadli** [comment] 2018-03-13 04:43
@overhound Info on the OS version + device language would be helpful. Tried successfully on Nexus 5 with OS 8.0.0 with (en-US).

**Comment by abangfadli** [comment] 2018-03-26 09:10
Closing this as I can't reproduce. Feel free to re-open if anyone found the same issue.

**Closed as completed by abangfadli** 2018-03-26 09:10 UTC
